name: valuta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  circular_reveal_animation: ^2.0.1
  flutter_toggle_tab: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_lints: ^2.0.0
  easy_localization: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/